parameters:
#    cerad_blog.example.class: Cerad\Bundle\BlogBundle\Example

services:
#    cerad_blog.example:
#        class: %cerad_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
